[cli.logs]
save_logs = true
path = "/workspaces/sfguide-devops-snowflake-data-projects/.snowflake/logs"
level = "info"

[cli.features]
enable_snowflake_projects = true

[connections.default]
    role = "ATTENDEE_ROLE"
    account = "sfsehol-summit25_data_projects_ci_cd_gpvbjn"
    user = "service_user"
    schema = "DEV"
    database = "UTILS"
    authenticator = "SNOWFLAKE_JWT"
    private_key_file = "/workspaces/sfguide-getting-started-with-devops-data-projects-in-snowflake/.snowflake/RSA_KEY.p8"